# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CSjiabin Blog
SEOTitle: 黄佳滨的博客 | CSjiabin Blog
header-img: img/post-bg-coffee.jpeg
email: qq1187712426@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keyword: "hjb, csjiabin, csjiabin Blog, 黄佳滨的博客, huangjiabin, 黄佳滨, html, css, javascript, js, JavaScript, Node, node, nodejs, h5, html5, 小程序, vue"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://csjiabin.github.com" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: "https://github.com/csjiabin/csjiabin.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: https://avatars1.githubusercontent.com/u/20592953?s=460&v=4      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     csjiabin
zhihu_username:     csjiabin
github_username:    csjiabin
jianshu_username:   f7f87e65552a

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

  # Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: csjiabin

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7bd18cd14435f89a4dfb                            #生成的clientID
  clientSecret: 87b3c3f9d0aa37f71d64aac84331b2e5e769b3a1    #生成的clientSecret
  repo: csjiabin.github.io    #仓库名称
  owner: csjiabin    #github用户名
  admin: csjiabin
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


  # 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 2620e69674d25088f870bef114e8ff89
bd_site_verification: jOkdRqaEJF

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto
ga_site_verification: xBT4GhYoi5qRD5tr338pgPM5OWHHIDR6mNg1a3euekI

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·csjiabin",
        href: "https://www.jianshu.com/u/f7f87e65552a"
    }
]